<?php
$_item = $block->getItem();
$_quote = $_item->getQuote();
$_imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$productImage = $_imageHelper->init($_item->getProduct(), 'category_page_list', ['height' => 100 , 'width'=> 100])->getUrl();
?>
<tr>
    <td class="item-image" style="width: 100px; padding-top: 20px; ">
        <a href="<?= $block->getProductUrl()?>">
            <img width="100px" src="<?=$productImage?>" title="<?= $block->escapeHtml($_item->getName()) ?>" alt="<?= $block->escapeHtml($_item->getName()) ?>" style="width: auto; height: auto; max-width: 100px;" />
        </a>
    </td>
    <td class="item-info<?php if ($block->getItemOptions()) : ?> has-extra<?php endif; ?>">
        <a href="<?= $block->getProductUrl()?>">
            <h2 class="product-name" style="font-size: 16px; color: #000;"><?= $block->escapeHtml($_item->getName()) ?></p>
        </a>
        <p class="sku" style="margin: 0px;"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($_item->getSku()) ?></p>
        <?php if ($_options = $block->getOptionList()) : ?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                    <dd style="padding-left: 15px;">
                        <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                            <?= /* @escapeNotVerified */  $_formatedOptionValue['full_view'] ?>
                        <?php else : ?>
                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                        <?php endif; ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty" style="text-align: center;"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
    <td class="item-price" style="text-align: right;">
        <?= /* @escapeNotVerified */  $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getRowTotal()); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
