<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \MGS\Landing\Block\Landing
 */
?>

<?php
$_categories = $block->getChildCategory();
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
?>

<?php //Block Config ?>
<?php $per_row = $block->getConfig('mgs_landing/general/per_row'); ?>
<?php $shortdes = $block->getConfig('mgs_landing/general/show_shortdes'); ?>
<?php $character = $block->getConfig('mgs_landing/general/character'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>
<?php $baseImageHover = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $blockObj= $block->getLayout()->createBlock('Funowls\Plp\Block\Plpdetails'); ?>
<?php 
    $blockId = rand() . time();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $useSlider = $this->getUseSlider();
    $perRow = $this->getPerrow();
    if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
        $columnCount = $perRow * $this->getNumberRow();
    }
    $image = 'category_page_grid';
    $_image = 'product_thumbnail_image';
    $size = $themeHelper->getImageSize($this->getRatio());
    $themeSettings = $themeHelper->getThemeSettings();
    $padding = $themeHelper->getImagePadding($this->getRatio());
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
<?php $size = $themeHelper->getImageSize(); ?>
<?php $padding = $themeHelper->getImagePadding(); ?>
<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>

<?php // Block Content ?>
<div class="landing-categories--grid">
    <div class="row">
        <?php $i =0; 
        $helper = $this->helper('Web\Base\Helper\Data');
        foreach ($_categories as $_category): ?>
            <?php if ($_category->getIsActive()): ?>
                <?php $i++; ?>
                <div class="categories-items-grid <?php echo $block->getColClass($i,'grid'); ?>">
                    <div class="landing-categories--item">
                        <div class="landing-categories-detail">
                            <h2>
                                <a href="<?php echo $block->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a>
                            </h2>
                            <?php if($shortdes): ?>
                                <?php $_description = $block->getCateDescription($_category->getId()); ?>
                                <?php if ($_description): ?>
                                    <div class="landing-categories--shortdes">
                                        <div class="category-description">
                                            <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($_category, $_description, 'description') ?>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endif ?>
                            <a class="btn btn-primary margin-top10" href="<?php echo $block->getCategoryUrl($_category) ?>"><?php echo __('Shop Now'); ?></a>
                        </div>

                        <!-- subcategory products -->
                        <?php
                            $cat_id = $_category->getId();
                            $categoryProducts = $helper->getProductByCategoryId($cat_id);
                        ?>
                        <div class="content-block deal-product-cat-block">
                            <div class="block widget mgs-products deal-products-grid products-grid">
                                <div class="products  list items product-items row row-col-lg-3">
                                    <?php
                                        $i=0; $j=0;
                                        foreach ($categoryProducts as $_product): 
                                        $i++; ?>
                                                <?php $discountAmt = $blockObj->getIsSpecialPrice($_product->getId()); ?>
                                        <?php $bestPriceGuarantee = $blockObj->getBestPriceGuarantee($_product->getId()); ?>
                                        <?php $confBrandName = $blockObj->getConfBrandName($_product->getId()); ?>
                                        <?php $confModelName = $blockObj->getConfModelName($_product->getId()); ?>
                                        <?php $confProPrice = $blockObj->getConfPriceName($_product->getId()); ?>
                                        
                                        <div class="item product product-item product-item-info col-lg-3 col-md-3 col-sm-4 col-xs-6 ">
                                            <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                                <?php
                                                    $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                                    $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                                                    $productImageHover = $_imagehelper->init($_product, $_image)->resize($size['width'], $size['height'])->getUrl();
                                                    if(!$lazyLoad){
                                                        $baseImage = $productImage;
                                                        $baseImageHover = $productImageHover;
                                                    }
                                                ?>
                                                <div class="product-top">
                                                    <?php 
                                                      if($bestPriceGuarantee)
                                                      {
                                                        $bestPriceGuaranteeImage = $this->getUrl().'pub/media/wysiwyg/bestPriceGuarantee_listing.png';
                                                        ?>
                                                        <div class="best-price-guarantee"><img class="best-price-guarantee-img" src="<?= $bestPriceGuaranteeImage; ?>" alt="Best Price Guarantee"></div>
                                                        <?php
                                                      }
                                                    ?>
                                                    <div class="discountAmount"><?php if(!empty($discountAmt)) { ?><div class="discount-amt"><?= $discountAmt; ?></div><?php } ?></div>
                                                    <?php if($themeHelper->getStoreConfig('mpanel/catalog/images_slides')== 1): ?>
                                                       <div class="owl-carousel list_gallery">
                                                            <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
                                                                <img src="<?php echo $productImageBase ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
                                                            </a>
                                                           <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('image'))): ?>
                                                               <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
                                                                <img src="<?php echo $productThumbnail ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail" data-src="<?php echo $productThumbnail ?>"/>
                                                               </a>
                                                           <?php endif;?>
                                                           
                                                          <?php if((basename($_product->getData('small_image')) != basename($_product->getData('image'))) && (basename($_product->getData('small_image')) != basename($_product->getData('thumbnail')))): ?>
                                                                <a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
                                                                    <img src="<?php echo $productImageSmall ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail" data-src="<?php echo $productImageSmall ?>"/>
                                                               </a>
                                                           <?php endif;?>
                                                           
                                                        </div>
                                                        
                                                    <?php else:?>
                                                     <a href="<?php echo $_product->getProductUrl() ?>" style="padding-bottom: <?php echo $padding; ?>;" class="product photo product-item-photo" tabindex="-1">
                                                        <img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
                                                        
                                                        <?php if(basename($_product->getData('thumbnail')) !=  'no_selection'): ?>
                                                            <?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
                                                                <img src="<?php echo $baseImageHover ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-hover-show<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImageHover ?>" />
                                                            <?php endif ?>
                                                        <?php endif ?>
                                                        
                                                        <div class="product-image-photo"></div>
                                                    </a>
                                                       
                                                    <?php endif;?>
                                                    <?php echo $themeHelper->getProductLabel($_product) ?>
                                                    <div class="brand-price-wrapper">
                                                    <div class="brand-wrap">
                                                        <div class="brandName"><?php if(!empty($confBrandName)) { echo $confBrandName;  } ?></div>
                                                        <div class="modelName"><?php if(!empty($confModelName)) { echo $confModelName;  } ?></div>
                                                    </div>
                                                    <div class="proPrice"></div>
                                                    </div>                          
                                                    <!-- <div class="proName"></div> -->
                                                    <?php $availableColor = $blockObj->countAvailableCount($_product->getId()); ?>
                                                    <?php if($availableColor): ?>
                                                    <div class="available-color"><?= $availableColor; ?> Colors</div>
                                                    <?php endif ?>
                                                    <?php if ($themeHelper->getStoreConfig('mpanel/catalog/disable_add_to_cart') == 0 && $themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect') == 0 && $themeHelper->getStoreConfig('mpanel/catalog/disable_button_cart_hover_effect') == 0): ?>
                                                        
                                                    <?php endif ?>
                                                    <?php if ($_product->isSaleable()): ?>
                                                        <div>
                                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
                                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                                <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                                <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                                                                <?php 
                                                                    $has_option = 0;
                                                                    if($_product->getTypeId() == 'simple'){
                                                                        $data = $_product->getData();
                                                                        $has_option = ( isset($data['has_options']) && $data['has_options'] == 1) ? 1 : 0;
                                                                    }
                                                                        

                                                                 ?>
                                                                <button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span class="icon pe-7s-shopbag"></span>
                                                                    <span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            </form>
                                                        </div>
                                                    <?php endif ?>
                                                </div>
                                                <div class="product details product-item-details">
                                                    <?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
                                                    <h5 class="product name product-item-name">
                                                        <a class="product-item-link"
                                                           href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                            <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                                        </a>
                                                    </h5>
                                                    
                                                    <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                                    
                                                    <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
                                                </div>
                                            
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach ?>
    </div>
</div>



