<?php
namespace RedChamps\GuestOrders\Model;

use Magento\Checkout\Model\Session;
use Magento\Framework\App\Config\ScopeConfigInterface;
use RedChamps\CustomerAccountGenerator\Model\GenerateFromOrder;

class CustomerAccountGenerator
{
    protected $customerFromOrder;

    /**
     * @var ConfigReader
     */
    private $configReader;
    /**
     * @var Session
     */
    private $checkoutSession;

    /**
     * @param GenerateFromOrder $customerFromOrder
     * @param ConfigReader $configReader
     * @param Session $checkoutSession
     */
    public function __construct(
        GenerateFromOrder $customerFromOrder,
        ConfigReader $configReader,
        Session $checkoutSession
    ) {
        $this->customerFromOrder = $customerFromOrder;
        $this->configReader = $configReader;
        $this->checkoutSession = $checkoutSession;
    }

    public function execute($order)
    {
        if ($this->configReader->getConfig("auto_customer_accounts/enabled")) {
            $order->setData("need_assignment", "0");
            $order->setData(
                "account_email_notification",
                $this->configReader->getConfig("auto_customer_accounts/email_notification")
            );
            $result = $this->customerFromOrder->execute($order);
            if($result) {
                $this->checkoutSession->setCustomerAutoGenerated(true);
            }
            return $result;
        }
    }
}
