<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $blockObj= $block->getLayout()->createBlock('Funowls\Pdp\Block\Pdpdetails'); ?>
<div class="price_guarantee">
	<?php
	    if($_product->getBestPriceGuarantee())
        {
            $bestPriceGuaranteeImage = $blockObj->getBaseUrl().'pub/media/wysiwyg/bestPriceGuarantee.jpeg';
            ?>
            <img src="<?= $bestPriceGuaranteeImage; ?>" alt="Price Guarantee">
            <?php
        }
	?>
</div>
<div class="sezzle-emi">
	<?php 
		if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){
            $proPrice = $_product->getFinalPrice();
	    }
	    else
	    {
	    	if($_product->getSpecialPrice())
            {
                $proPrice = $_product->getSpecialPrice();
            }
	        else
	        {
	        	$proPrice = $_product->getPrice();
	        } 
	    }
	    $proFinalPrice = number_format((float)$proPrice/4, 2, '.', '');

	?>
	<div class="sezzle-emi-info-button"><div class="sezzle-emi-button-wrapper sezzle-modal-link" style="cursor: pointer;"><div class="sezzle-button-text">or 4 interest-free payments of &nbsp; <span class="sezzle-payment-amount sezzle-button-text">CAD $<?= $proFinalPrice; ?>&nbsp;</span> with <img class="sezzle-logo szl-light-image" src="https://media.sezzle.com/branding/2.0/Sezzle_Logo_FullColor.svg" style="transform-origin: right top; transform: scale(1);"> <code class="sezzle-info-icon"><div class="tooltip-custom">ⓘ
  <span class="tooltiptext">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span>
</div></code></div></div></div>
</div>