<?php
/**
 * @var $block \Magenest\InstagramShop\Block\Photo\Slider
 */
$photos      = $block->getPhotos();
$slickConfig = $block->getData();
?>
    <div class="slider">
        <?php
        echo $block->getSharePopup();
        ?>
    </div>
    <div class="block block-photo-slider slider-list container">
        <div class="block-title">
            <h2 style="text-align: center"><?php echo $block->getTitle() ?></h2>
        </div>
        <div class="block-content">
            <?php if ($photos->getSize() > 0) { ?>
                <ul class="slides owl-carousel">
                    <?php
                    /** @var \Magenest\InstagramShop\Model\Photo $photo */
                    foreach ($photos as $photo) { ?>
                        <li id="<?= $photo->getPhotoId() ?>">
                            <a href="<?= $photo->getUrl() ?>">
                                <img src="<?= $photo->getSource() ?>" class='post-img' />
                                <div class="overlay"></div>
                                <div class="text">
                                    <img src="<?= $this->getViewFileUrl('Magenest_InstagramShop::images/instagram.png') ?>">
                                    <button><?= $block->getHoverText() ?></button>
                                </div>
                            </a>
                            <?= $block->getLayout()->createBlock(\Magenest\InstagramShop\Block\Instagram\LinkedProducts::class)->setProductList($photo->getProductIds())->toHtml() ?>
                        </li>
                    <?php } ?>
                </ul>
                <div style="text-align:center">
                    <a href="<?= $block->getBaseUrl() ?>instagram/gallery/" class="instagram-button"
                       style="<?= $block->getViewFullGalleryCss() ?>">
                        <?= $block->getViewFullGalleryTitle() ?>
                    </a>
                </div>
            <?php } ?>
        </div>
    </div>

<?php if ($photos->getSize()) : ?>
    <script>
        require(['jquery'], function ($) {
            $(function () {
                require(['jquery', 'mageplaza/core/owl.carousel'], function($) {
                    $('.slides').owlCarousel({
                        "autoWidth": 0,
                        "autoHeight": 1,
                        "loop": 1,
                        "nav": 1,
                        "dots": 0,
                        "margin":10,
                        "lazyLoad": 0,
                        "autoplay": 1,
                        "autoplayTimeout": 5000,
                        "navText" : ["<i class='fa fa-chevron-left'></i>","<i class='fa fa-chevron-right'></i>"],
                        "responsive": {
                            "1024": {
                                "items": "5"
                            },
                            "768": {
                                "items": "4"
                            },
                            "568": {
                                "items": "2"
                            },
                            "320": {
                                "items": "1"
                            }
                        },
                        "animateOut": "fadeOut"
                    });

                    var photos = <?=json_encode($photos->getData())?>;
                    $('.slides .owl-item li a').on('click', function (e) {
                        var self = this;
                        e.preventDefault();
                        var photo = $.map(photos, function (item) {
                            if ($(self).parent().attr('id') === item.photo_id) {
                                return item;
                            }
                        });
                        photo = photo[0];
                        $('.slider #widget-instagram-image-url').attr('src', photo.source);
                        var html = $(self).parent().children('#linked-products').html();
                        // remove all white space, tab, new line...
                        if (html.replace(/[\r\n]+/g, '').trim() !== '') {
                            $('.slider .featured-products').show();
                            $('.slider .widget-text-link-container').html(html);
                        } else {
                            $('.slider .featured-products').hide();
                            $('.slider .widget-text-link-container').html('');
                        }
                        $('.slider #widget-instagram-url').attr('href', photo.url);
                        $('.slider .widget-detail-title').text(photo.caption ? photo.caption : '');
                        $('.slider #created_at_instagram').text(photo.created_at);
                        $('.slider #widget-timeline-detail').data('photo-id', photo.photo_id).removeClass('widget-hidden');
                    });
                    $('.slider #widget-detail-close').on('click', function () {
                        $('.slider #widget-timeline-detail').addClass('widget-hidden');
                    });

                    $('.slider #widget-prev-post').on('click', function () {
                        var photoId = $('.slider #widget-timeline-detail').data('photo-id');
                        $.map(photos, function (item, index) {
                            if (item.photo_id === photoId) {
                                var id = index === 0 ? photos.length : index;
                                return $('.flex-viewport > ul > li#' + photos[id - 1].photo_id + ' > a').trigger('click');
                            }
                        });
                    });
                    $('.slider #widget-next-post').on('click', function () {
                        var photoId = $('.slider #widget-timeline-detail').data('photo-id');
                        $.map(photos, function (item, index) {
                            if (item.photo_id === photoId) {
                                var id = index === photos.length - 1 ? -1 : index;
                                return $('.flex-viewport > ul > li#' + photos[id + 1].photo_id + ' > a').trigger('click');
                            }
                        });
                    });

                });

            });
        });
    </script>
<?php endif; ?>