<div id="prx">
<!-- This page calling from: app/design/frontend/Mgs/cheapglasses/Magento_Catalog/templates/product/view/addtocart.phtml -->
	<?php
	
	function isMobileDevice(){
    $aMobileUA = array(
        '/iphone/i' => 'iPhone', 
        '/ipod/i' => 'iPod', 
        '/ipad/i' => 'iPad', 
        '/android/i' => 'Android', 
        '/blackberry/i' => 'BlackBerry', 
        '/webos/i' => 'Mobile'
    );

    //Return true if Mobile User Agent is detected
    foreach($aMobileUA as $sMobileKey => $sMobileOS){
        if(preg_match($sMobileKey, $_SERVER['HTTP_USER_AGENT'])){
            return true;
        }
    }
    //Otherwise return false..  
    return false;
}

		$product_id = $this->getRequest()->getParam('id');

		$productData = $this->getProductData($product_id);
		$product_name = $productData->getName();
		$product_url = $productData->getProductUrl();
		//$product_image_url = $this->getProductImg($productData);
		$product_price = $productData->getFinalPrice();
		$product_price_format = $this->getProductPriceFormat($product_price);
	
		$customer_id = $this->getCustomerId();
	
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
	
		$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
		$currentStore = $storeManager->getStore();
		$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	
		$addToCartUrl =  $listBlock->getAddToCartUrl($productData);

		$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
		$product_image_url = $_imagehelper->init($productData, 'product_base_image')->resize(700, 350)->getUrl();
	?>
	<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
	<div class="prx-container container">
	
		<div class="prx-main">

			<!-- Top Title Section -->
			<div class="prx-title">
				<div class="prx-step-status">
					<div class="step-status-line">
						<div class="step-status-inline"></div>
					</div>
					<div class="bottom-step-action">
						<span style="display:none;" class="action-back previous-step"><span class="fa fa-angle-left"></span></span>
						<span class="action-next next-step"><span class="fa fa-angle-right"></span></span>
					</div>
					<ul class="step-container triggers">
						<!-- step-current-->
						<li class="prx-title-usage step-completed current" id="step-title-1">
							<div class="step-status-detail event-prx-normal">
								<span class="icon-wrapper"><i class="icon">1</i></span>
								<span class="step-name">Usage</span>
							</div>
						</li>
						<li class="prx-title-lenstype step-disable" id="step-title-2">
							<div class="step-status-detail event-prx-normal">
								<span class="icon-wrapper"><i class="icon">2</i></span>
								<span class="step-name">Lens Type</span>
							</div>
						</li>
						<li class="prx-title-lensthickness step-disable" id="step-title-3">
							<div class="step-status-detail event-prx-normal">
								<span class="icon-wrapper"><i class="icon">3</i></span>
								<span class="step-name">Lens Thickness</span>
							</div>
						</li>
						<li class="prx-title-prescription step-disable" id="step-title-4">
							<div class="step-status-detail event-prx-normal">
								<span class="icon-wrapper"><i class="icon">4</i></span>
								<span class="step-name">Prescription</span>
							</div>
						</li>
						<li class="prx-title-last step-disable" id="step-title-5" style="visibility:hidden; width:0px;">
							<div class="step-status-detail event-prx-normal">
								<span class="icon-wrapper"><i class="icon">5</i></span>
								<span class="step-name">Last Step</span>
							</div>
						</li>
					</ul>
				</div>
			</div>
			
			
			<!-- Container Section Loading Dynamically -->
			<div class="prx-step-section">
				<div id="prx-steps" style="width:100%;">
				
					<?php
					$lensusageData = $this->getLensusageData($product_id);
					if(isset($lensusageData)) {
						$lensusageData = $lensusageData->getData();
					}
					if( is_array($lensusageData) && count($lensusageData) > 0 ) {
						?>
						<!-- Step 1 -->
						<ul data_index="0" class="prx-sub-options step-state" id="step-status-1">
						
						<?php
						foreach($lensusageData as $key => $value) {
							$lensusage_id = $value['lensusage_id'];
								?>
							<li lensusage_id='<?php echo $value['lensusage_id']; ?>' title='<?php echo $value['lensusage_title']; ?>'>
								<div class="event_prx_main event-prx">
									
									<div class="desc">
										<?php if(isset($value['youtube_content']) && $value['youtube_content'] != '') { ?>
											<a href="#lensusage<?php echo $lensusage_id; ?>" title="<?php echo $value['lensusage_subtitle']; ?>"
												data-fancybox="lensusage<?php echo $lensusage_id; ?>" class="vid-ico"></a>
											<!--Youtube Content-->
											<div id="lensusage<?php echo $lensusage_id; ?>" style="display: none;">
												<?php echo $value['youtube_content']; ?>
											</div>
										<?php } else { ?>
											<a class="info-ico" data-title="<?php echo $value['lensusage_subtitle']; ?>"></a>
										<?php } ?>
									</div>
									<div class="option-description">
										<?php
										$img = $value['image'];
										$fullImgPath = $mediaUrl . $img;
										$imageExit = 0;
										if($img != ''){ 
											$imageExit=1;?>
										<img src="<?php echo $fullImgPath; ?>" alt="" style="max-width:100%; min-width:80px;" />
										<?php }?>
										<div class="option-content <?php echo ($imageExit)?'':'aligncenter'?>">
											<div class="option-title">
												<span class="option-name"><?php echo $value['lensusage_title']; ?></span>
											</div>
											<p class="option-intro"><?php echo $value['lensusage_subtitle']; ?></p>
										</div>
									</div>
									<div class="option-price">
										<span class="option-name">+$<span><?php echo $value['lensusage_price']; ?></span></span>
									</div>
								</div>
							</li>
							<?php
						}
						?>
						</ul>
						<?php 
					}
					?>
					
					
					<?php
					$lenstypeData = $this->getLenstypeData($product_id);
					if(isset($lenstypeData)) {
						$lenstypeData = $lenstypeData->getData();
					}
					
					if(isset($lenstypeData) && is_array($lenstypeData) && count($lenstypeData) > 0 ) {
						?>
						<!-- Step 2 -->
						<ul data_index="1" class="prx-sub-options step-state" id="step-status-2" style="display:none;">
						
						<?php
						foreach($lenstypeData as $key => $value) {
							$lenstype_id = $value['lenstype_id'];
							?>
							<li lensusage_id='<?php echo $value['lensusage_id']; ?>' lenstype_id='<?php echo $value['lenstype_id']; ?>' title='<?php echo $value['lenstype_title']; ?>'>
								<div class="event_prx_main event-prx">
									
									<div class="desc">
										<?php if(isset($value['youtube_content']) && $value['youtube_content'] != '') { ?>
											<a href="#lenstype<?php echo $lenstype_id; ?>" title="<?php echo $value['lenstype_subtitle']; ?>"
												data-fancybox="lenstype<?php echo $lenstype_id; ?>" class="vid-ico"></a>
											<!--Youtube Content-->
											<div id="lenstype<?php echo $lenstype_id; ?>" style="display: none;">
												<?php echo $value['youtube_content']; ?>
											</div>
										<?php } else { ?>
											<a class="info-ico" title="<?php echo $value['lenstype_subtitle']; ?>"></a>
										<?php } ?>
									</div>
									<div class="option-description">
										<?php
										$img = $value['image'];
										$fullImgPath = $mediaUrl . $img;
										$imageExit = 0;
										?>
										<?php if($img != ''){ $imageExit=1; ?>
										<img src="<?php echo $fullImgPath; ?>" alt="" style="max-width:100%; min-width:80px;" />
										<?php }?>
										<div class="option-content <?php echo ($imageExit)?'':'aligncenter'?>">
											<div class="option-title">
												<span class="option-name"><?php echo $value['lenstype_title']; ?></span>
											</div>
											<p class="option-intro"><?php echo $value['lenstype_content']; ?></p>
										</div>

									</div>
									<div class="option-price">
										<span class="option-name">+$<span><?php echo $value['lenstype_price']; ?></span></span>
									</div>
								</div>
								
								<?php
								$confirmButton = false;
								
								$lenstintstrengthData = $this->getLenstintstrengthData($lenstype_id);
								if(isset($lenstintstrengthData)) {
									$lenstintstrengthData = $lenstintstrengthData->getData();
								}
								
								$lenstintcolorData = $this->getLenstintcolorData($lenstype_id);
								if(isset($lenstintcolorData)) {
									$lenstintcolorData = $lenstintcolorData->getData();
								}
								
								if( (isset($lenstintstrengthData) && is_array($lenstintstrengthData) && count($lenstintstrengthData) > 0)
									||
									(isset($lenstintcolorData) && is_array($lenstintcolorData) && count($lenstintcolorData) > 0)
								)
								{
									$confirmButton = true;
								}
								
								if($confirmButton) { ?>
								<div class="event-prx lenstype-sub-content" style="display:none;">
									<div class="prx-tint-option">
										<?php if(isset($lenstintstrengthData) && is_array($lenstintstrengthData) && count($lenstintstrengthData) > 0 )
										{
											?>
											<div class="prx-strength">
												<strong class="prx-strength-title">Tint Strength:</strong>
												<div class="prx-select-content1">
												<!-- null value for tint-strength -->
												<input id="lenstintstrength_default" class="opacityhide" type="radio" name="lenstintstrength" value="" checked />
												<?php
													foreach($lenstintstrengthData as $key => $value) {
													?>
													<label for="lenstintstrength_<?php echo $value['lenstintstrength_id']; ?>">
													<span title="<?php echo $value['lenstintstrength_title']; ?>" class="tint-strength <?php echo $value['lenstintstrength_title']; ?>">
														<input id="lenstintstrength_<?php echo $value['lenstintstrength_id']; ?>" class="opacityhide" type="radio" 
															   name="lenstintstrength" value="<?php echo $value['lenstintstrength_title']; ?>" />
														<?php echo $value['lenstintstrength_title']; ?>
													</span>
													</label>
												<?php } ?>
												</div>
											</div>
											<?php
										}
										?>
										
										<?php if(isset($lenstintcolorData) && is_array($lenstintcolorData) && count($lenstintcolorData) > 0 )
										{
											?>
											<div class="prx-color">
												<strong class="prx-color-title">Tint Color:</strong>
												<div class="prx-select-content2">
												<!-- null value for tint-strength -->
												<input id="lenstintcolor_default" class="opacityhide" type="radio" name="lenstintcolor" value="" checked />
												<?php
													foreach($lenstintcolorData as $key => $value) {
													?>
													<label for="lenstintcolor_<?php echo $value['lenstintcolor_id']; ?>">
													<span title="<?php echo $value['lenstintcolor_title']; ?>" class="tint-color <?php echo $value['lenstintcolor_title']; ?>" style="background:<?php echo $value['lenstintcolor_title']; ?> ">
														<input id="lenstintcolor_<?php echo $value['lenstintcolor_id']; ?>" class="opacityhide" type="radio"
															   name="lenstintcolor" value="<?php echo $value['lenstintcolor_title']; ?>" >
														<?php echo $value['lenstintcolor_title']; ?>
													</span>
													</label>
												<?php } ?>
												</div>
											</div>
											<?php
										}
										?>
										
										<div><button type="button" class="prx-confirm-btn tint_confirm">Confirm</button></div>
										
									</div>
								</div>
								<?php } ?>
								
							</li>
							<?php
						}
						?>
						</ul>
						<?php 
					}
					?>
					
					
					<?php
					$lensthicknessData = $this->getLensthicknessData($product_id);
					if(isset($lensthicknessData)) {
						$lensthicknessData = $lensthicknessData->getData();
					}
					if( is_array($lensthicknessData) && count($lensthicknessData) > 0 ) {
						?>
						<!-- Step 3 -->
						<ul data_index="2" class="prx-sub-options step-state" id="step-status-3" style="display:none;">
						
						<?php
						foreach($lensthicknessData as $key => $value) {
							$lensthickness_id = $value['lensthickness_id'];
						?>
							<li lenstype_id='<?php echo $value['lenstype_id']; ?>' lensthickness_id='<?php echo $value['lensthickness_id']; ?>' title='<?php echo $value['lensthickness_title']; ?>'>
								<div class="event_prx_main event-prx">
								
									<div class="desc">
										<?php if(isset($value['youtube_content']) && $value['youtube_content'] != '') { ?>
											<a href="#lensthickness<?php echo $lensthickness_id; ?>" class="vid-ico" 
											 title='<?php echo $value['lensthickness_subtitle']; ?>' data-fancybox="lensthickness<?php echo $lensthickness_id; ?>" ></a>
											<!--Youtube Content-->
											<div id="lensthickness<?php echo $lensthickness_id; ?>" style="display: none;">
												<?php echo $value['youtube_content']; ?>
											</div>
										<?php } else { ?>
											<a class="info-ico"  title='<?php echo $value['lensthickness_subtitle']; ?>'></a>
										<?php } ?>
									</div>
									
									
									<div class="option-description">
										<?php $img = $value['image'];
											  $fullImgPath = $mediaUrl . $img;
											  $imageExit=0;
										?>
										<?php if($img != ''){ $imageExit=1; ?>
										<img src="<?php echo $fullImgPath; ?>" alt="" style="max-width:100%; min-width:80px;" />
										<?php }?>

										<div class="option-content <?php echo ($imageExit)?'':'aligncenter'?>">
											<div class="option-title">
												<span class="option-name"><?php echo $value['lensthickness_title']; ?></span>
											</div>
											<p class="option-intro"><?php echo $value['lensthickness_content']; ?></p>
										</div>
									</div>
									<div class="option-price">
										<span class="option-name">+$<span><?php echo $value['lensthickness_price']; ?></span></span>
									</div>
								</div>
							</li>
							<?php
						}
						?>
						</ul>
						<?php 
					}
					?>
					<?php
					$lensprescriptionData = $this->getLensprescriptionData();
					if(isset($lensprescriptionData)) {
						$lensprescriptionData = $lensprescriptionData->getData();
					}
					if(isset($lensprescriptionData) && is_array($lensprescriptionData) && count($lensprescriptionData) > 0 ) {
						?>
						<!-- Step 4 -->
						<ul data_index="3" class="prx-sub-options step-state" id="step-status-4" style="display:none;">
						
						<?php
						$add_class = "";
						foreach($lensprescriptionData as $key => $value) {
							/* if($value['lensprescription_identifier'] == 'use_saved' && $customer_id) {
								$add_class = "use_saved_prx";
								$value['lensprescription_content'] = 'Hello, Please use previous prx';
							} */
								?>
							<li id='<?php echo $value['lensprescription_identifier']; ?>' class='<?php echo $add_class; ?>' title='<?php echo $value['lensprescription_title']; ?>'>
								<div class="event-prx">
									<div class="option-description">
										<div class="option-content">
											<div class="option-title">
												<span class="option-name"><?php echo $value['lensprescription_title']; ?></span>
											</div>
											<p class="option-intro"><?php echo $value['lensprescription_content']; ?></p>
										</div>
									</div>
								</div>
							</li>
							<?php
						}
						?>
						</ul>
						<?php 
					}
					?>
					
					<!-- Step 5 -->
					<ul data_index="4" class="step-state" id="step-status-5" style="display:none;">
						<?php echo $this->getLayout()->createBlock("Webindiainc\Prx\Block\Prxdata")->setTemplate("Webindiainc_Prx::prxdata.phtml")->toHtml(); ?>
					</ul>
				</div>
			</div>
			<?php //echo $this->getLayout()->createBlock("Webindiainc\Prx\Block\Prxdata")->setTemplate("Webindiainc_Prx::prxdata.phtml")->toHtml(); ?>
			
			
		</div>
		<!-- Payment Section Right Side -->
		<div class="prx-sidebar">
			
			<div class="prx-product">
				<div class="product-head clearfix">
					<h1><span class="product-name uppercase" itemprop="name"><?php echo $product_name; ?></span></h1>
				</div>
			</div>
			<div class="prx-preview-content">
				<div class="prx-frame-preview">
					<img id="frame-image" src="<?php echo $product_image_url; ?>" alt="Product Name">
				</div>
				<div class="prx-back-detail">
					<i class="pe-7s-angle-left"></i><a class="event-prx-normal" href="<?php echo $product_url; ?>" id="back_product_page">Back to Frame Description</a>
				</div>
			</div>
			<div class="prx-total clearfix" id="prx-total">
				<h1 class="product-title-mobile"><span class="product-name uppercase" itemprop="name"><?php echo $product_name; ?></span></h1>
				<div class="separately-price">
					<p class="frame">Frame Price: <strong class="price price-symbol" id="frame-price"><span><?php echo $product_price_format; ?></span></strong></p>
					<p class="frame">Lens Price: <strong class="price price-symbol" id="lens-price">$<span>0.00</span></strong> <span class="toggle-details">Details</span></p>
				</div>
				<div class="prx-show-selected" style="display: none;">
					<ul>
						<li class="prx_types"></li>
						<li class="prx_types"></li>
						<li class="prx_types"></li>
						<li class="prx_types"></li>
					</ul>
				</div>
				<div class="final-price">
					TOTAL: <strong class="price final price-symbol" id="total_prescription_price"><span><?php echo $product_price_format; ?></span></strong>
				</div>
				
					<?php echo $block->getBlockHtml('formkey')?>
					
					<input type='hidden' name='product' id='product' value='<?php echo $product_id; ?>' />
					<input type="hidden" name="istint_strength_exist" id="istint_strength_exist" value="" />
					<input type="hidden" name="istint_color_exist" id="istint_color_exist" value="" />
					<input type='hidden' name='lensusagetitle' id='lensusagetitle' value='' />
					<input type='hidden' name='lensusageprice' id='lensusageprice' value='' />
					<input type='hidden' name='lenstypetitle' id='lenstypetitle' value='' />
					<input type='hidden' name='lenstypeprice' id='lenstypeprice' value='' />
					<input type='hidden' name='lensthicknesstitle' id='lensthicknesstitle' value='' />
					<input type='hidden' name='lensthicknessprice' id='lensthicknessprice' value='' />
					<input type='hidden' name='prxdata[send_via]' id='send_via' value='' />
					<input type='hidden' name='prxdata[send_via_title]' id='send_via_title' value='' />
					<input type='hidden' name='frameprice' id='frameprice' value='<?php echo $product_price; ?>' />
					<input type='hidden' name='lenstotalprice' id='lenstotalprice' value='' />
					<button type="submit" title="Add to Cart" id="prx_submit_btn" class="btn event-cart-prx action tocart primary disabled" disabled="disabled">
						<span>Add to Cart</span>
					</button>
			</div>
			<div class="customer_chat">
				<span class="chat-icon"></span><?php echo __('Need Help? Start a <a href="javascript:$zopim.livechat.window.show();">Live Chat</a>'); ?>
			</div>
		</div>
		
	</div>
					</form>
</div>

<script type="text/javascript">
    require(['jquery','fancybox','customjs'], function($) {
		$(document).on('click',".prx-step-status li.step-completed", function(){
			var step_title = $(this).attr('id');
			var step_status = step_title.replace("title", "status");
			var isCurrentStepTitle = $(this).hasClass('current');
			if(!isCurrentStepTitle) {
				setPrevNext(step_status, 'previous');
			}
			if(!$(this).hasClass("prx-title-prescription")) {
				$("#prx_submit_btn").addClass('disabled');
				$("#prx_submit_btn").attr("disabled", true);
			}
		});
		
		$("#step-status-1 li div.event_prx_main").click(function(){
			var lensusage_id = $(this).parent('li').attr('lensusage_id');
			var isExistLensSelectedClass = $(this).hasClass('lens_selected');
			if(!isExistLensSelectedClass) {
				setLensSelectionTitle($(this));
				setLensSelectionPrice($(this));
			}
			
			var lensusagetitle = $(this).find('.option-title .option-name').html();
			var lensusageprice = parseFloat($(this).find('.option-price .option-name span').html());
			$("#lensusagetitle").val(lensusagetitle);
			$("#lensusageprice").val(lensusageprice);

			if(!isExistLensSelectedClass) {
				$("#step-status-2 li").each(function() {
					if( lensusage_id != $(this).attr('lensusage_id') ) {
						$(this).hide();
					} else {
						$(this).show();
					}
				});
				$('#step-title-2').nextAll('li').removeClass('step-completed').addClass('step-disable');
				$('#step-title-2').removeClass('step-disable').addClass('step-completed');
			}
			setPrevNext('step-status-2');
		});
		
		$("#step-status-2 li div.event_prx_main").click(function(){
			var istint_strength_exist = $(this).parent('li').find('.lenstype-sub-content').find('.prx-strength').html();
		if( istint_strength_exist == 'undefined' || !istint_strength_exist || istint_strength_exist == '' ) {
				$("#istint_strength_exist").val('no');
			} else {
				$("#istint_strength_exist").val('yes');
			}
			var istint_color_exist = $(this).parent('li').find('.lenstype-sub-content').find('.prx-color').html();
			if( istint_color_exist == 'undefined' || !istint_color_exist || istint_color_exist == '' ) {
				$("#istint_color_exist").val('no');
			} else {
				$("#istint_color_exist").val('yes');
			}
			
			var lenstype_id = $(this).parent('li').attr('lenstype_id');
			var isExistLensSelectedClass = $(this).hasClass('lens_selected');
			if(!isExistLensSelectedClass) {
				setLensSelectionTitle($(this));
				setLensSelectionPrice($(this));
			}
			var lenstypetitle = $(this).find('.option-title .option-name').html();
			var lenstypeprice = parseFloat($(this).find('.option-price .option-name span').html());
			$("#lenstypetitle").val(lenstypetitle);
			$("#lenstypeprice").val(lenstypeprice);
			
			$(this).parents('ul').find('.lenstype-sub-content').hide();
			
			if ($(this).parent('li').find('.lenstype-sub-content').length > 0){
				$(this).parent('li').find('.lenstype-sub-content').show();
			} else {
				if(!isExistLensSelectedClass) {
					$("#step-status-3 li").each(function() {
						if( lenstype_id != $(this).attr('lenstype_id') ) {
							$(this).hide();
						} else {
							$(this).show();
						}
					});
					$('#step-title-3').nextAll('li').removeClass('step-completed').addClass('step-disable');
					$('#step-title-3').removeClass('step-disable').addClass('step-completed');
				}
				setPrevNext('step-status-3');
			}
		});
		
		$(".prx-color").find(".tint-color").click(function(){
			$(this).parents('.prx-color').find('.tint-color').removeClass("checked");
			$(this).addClass("checked");
		});
		
		$(".prx-strength").find(".tint-strength").click(function(){
			$(this).parents('.prx-strength').find('.tint-strength').removeClass("checked");
			$(this).addClass("checked");
		});
											   
		$(".tint_confirm").click(function(){
			
			/* tint color & strength validation : start */
			var isTintStrengthExist = $(this).parents('.prx-tint-option').find('.prx-strength');
			var isTintColorExist = $(this).parents('.prx-tint-option').find('.prx-color');
			var tintStrengthVal = '';
			var tintColorVal = '';
			var isTintProcess = false;
			
			if($(isTintStrengthExist).html() != undefined) {
				isTintProcess = true;
				var ts = true;
				tintStrengthVal = $("input[name*='lenstintstrength']:checked").val();
			}
			if($(isTintColorExist).html() != undefined) {
				isTintProcess = true;
				var tc = true;
				tintColorVal = $("input[name*='lenstintcolor']:checked").val();
			}
			if(ts) {
				if(tintStrengthVal == '') {
					alert('please select tint option');
					return false;
				}
			}
			if(tc) {
				if(tintColorVal == '') {
					alert('please select tint option');
					return false;
				}
			}
			if(!isTintProcess) {
				$("input[name*='lenstintstrength']").val('');
				$("input[name*='lenstintcolor']").val('');
			}
			/* tint color & strength validation : end */
			
			var lenstype_id = $(this).parents('li').attr('lenstype_id');
			$("#step-status-3 li").each(function() {
				if( lenstype_id != $(this).attr('lenstype_id') ) {
					$(this).hide();
				} else {
					$(this).show();
				}
			});
			$('#step-title-3').removeClass('step-disable').addClass('step-completed');
			setPrevNext('step-status-3');
		});
		

		$("#step-status-3 li div.event_prx_main").click(function(){
			var lensthickness_id = $(this).parent('li').attr('lensthickness_id');
			var isExistLensSelectedClass = $(this).hasClass('lens_selected');
			if(!isExistLensSelectedClass) {
				setLensSelectionTitle($(this));
				setLensSelectionPrice($(this));
			}
			var lensthicknesstitle = $(this).find('.option-title .option-name').html();
			var lensthicknessprice = parseFloat($(this).find('.option-price .option-name span').html());
			$("#lensthicknesstitle").val(lensthicknesstitle);
			$("#lensthicknessprice").val(lensthicknessprice);
			
			if(!isExistLensSelectedClass) {
				$('#step-title-4').removeClass('step-disable').addClass('step-completed');
			}
			setPrevNext('step-status-4');
		});

		$("#step-status-4 li div.event-prx").click(function(){
			$(this).parents('ul').find('li div.event-prx').removeClass('lens_selected');
			$(this).addClass('lens_selected');
			var send_via_id = $(this).parent('li').attr('id');
			var send_via_title = $(this).parent('li').attr('title');
			if( $(this).parent('li').attr('id') == 'enter_online' ) {
				setPrevNext('step-status-5');
				$("#prx_submit_btn").addClass('disabled');
				$("#prx_submit_btn").attr("disabled", true);
			} else {
				$("#prx_submit_btn").removeClass('disabled');
				$("#prx_submit_btn").removeAttr("disabled");
			}
			$('#send_via').val(send_via_id);
			$('#send_via_title').val(send_via_title);
		});
		
		$("li.use_saved_prx div.event-prx").click(function(){
			$("#prx_submit_btn").addClass('disabled');
			$("#prx_submit_btn").attr("disabled", true);
		});
		
		$("#prxdata_confirm").click(function() {
			var rightcyl = $('#rightcyl').val();
			var leftcyl = $('#leftcyl').val();
			var rightaxis = $('#rightaxis').val();
			var leftaxis = $('#leftaxis').val();
			
			if(rightcyl == '0.00' || rightcyl == '00 Plano' || rightcyl == 'None' || rightcyl == 'SPH' || 
				rightcyl == 'DS' || rightcyl == 'Balance' || rightcyl == 'Infinity') {
			
			} else {
				if(rightaxis == 'None') {
					isRxOK = false;	
					var errorMessage = 'Please Choose Right Axis Option';
					alert(errorMessage);
					return false;
				}
			}
			if(leftcyl == '0.00' || leftcyl == '00 Plano' || leftcyl == 'None' || leftcyl == 'SPH' || 
				leftcyl == 'DS' || leftcyl == 'Balance' || leftcyl == 'Infinity') {
				
			}  else {
				if(leftaxis == 'None') {
					isRxOK = false;	
					var errorMessage = 'Please Choose Left Axis Option';
					alert(errorMessage);
					return false;
				}
			}
			$("#prx_submit_btn").removeClass('disabled');
			$("#prx_submit_btn").removeAttr("disabled");
		});
		
		$('#both_pd').change(function() {
			if($(this).is(":checked")) {
				$("#pdcommon").parent().hide();
				$("#pdleft").parent().show();
				$("#pdright").parent().show();
			} else {
				$("#pdcommon").parent().show();
				$("#pdleft").parent().hide();
				$("#pdright").parent().hide();
			}
    	});
		
		$('#prismprice').change(function() {
			var prismpricevalue = parseInt($("#prismpricevalue").val());
			var lenstotalprice = parseInt($("#lenstotalprice").val());
			var frameprice = parseInt($("#frameprice").val());
			
			if($(this).is(":checked")) {
				var newLenstotalprice = lenstotalprice + prismpricevalue;
				$(".prx-show-selected ul").append('<li class="prx_types_prism">add prism</li>');
			} else {
				var newLenstotalprice = lenstotalprice - prismpricevalue;
				$('.prx_types_prism').remove();
			}
			
			$("#lenstotalprice").val(newLenstotalprice);
			$("#total_prescription_price").html('$' + newLenstotalprice);
			
			var onlylensprice = newLenstotalprice - frameprice;
			$("#lens-price span").html(onlylensprice);
  		});
		
		function setLensSelectionTitle(current){
			var title = $(current).find('.option-title .option-name').html();
			var parentUl = $(current).parents('ul');
			var data_index = parentUl.attr('data_index');
			var parentId = parentUl.attr('id');
			var edit = '<a href="javascript:void(0)" class="edit" data-index="'+data_index+'">Edit</a>';
			$('.prx-show-selected ul li.prx_types').each(function(index) {
				if(index > data_index) {
					$(this).html('');
				} else if(index == data_index) {
					$(this).html(title+edit);
					$(this).find('a').click(function (){
						var dataIndex = $(this).attr('data-index');
						dataIndex = parseInt(dataIndex)+1
						var editClick = $('#step-title-'+dataIndex);
						if(editClick.length){
							editClick.trigger('click');
						}
					});
				}
			});
		}
		
		function setLensSelectionPrice(current){
			var price = 0;
			var lens_price_total = 0;
			$(current).parents('ul').find('li div.event_prx_main').removeClass('lens_selected');
			$(current).addClass('lens_selected');
			var data_index = $(current).parents('ul').attr('data_index');

			$('ul.step-state').each(function(index) {
				if(index <= data_index) {
					price = $(this).find('li div.lens_selected').find('.option-price .option-name span').html();
					lens_price_total += parseFloat(price);
				} else {
					$(this).find('li div.lens_selected').removeClass('lens_selected');
				}
			});
			lens_price_total = lens_price_total.toFixed(2);
			$('#lens-price').find('span').html(lens_price_total);
			
			var framePrice = parseFloat('<?php echo $product_price; ?>');
			var totalPrice = parseFloat(framePrice) + parseFloat(lens_price_total);
			totalPrice = totalPrice.toFixed(2);
			$('#total_prescription_price').html('$' + totalPrice);
			$('#lenstotalprice').val(totalPrice);
		}
		
		function setPrevNext(status, position = ''){
			var statusCurrent = status;
			var titleCurrent = status.replace("status", "title");
			$('#'+titleCurrent).addClass('current');
			
			$("#prx-steps ul").hide();
			if(position == 'previous') {
				$('#'+statusCurrent).css('left', '-777px');
			} else {
				$('#'+statusCurrent).css('left', '777px');
			}
			$('#'+statusCurrent).show();
			$("#"+statusCurrent).animate({ left: '0px'}, 'slow', 'linear');
			
			var index = parseInt(status.replace("step-status-", ""));
			var steps = $('#step-status-'+index);
			var track = $('#step-title-'+index);

			$('ul.step-container li').removeClass('current');
			track.addClass('current');
			
			if(index==1){
				$('.previous-step').attr('data-index',index);
				$('.next-step').attr('data-index',index+1);
			}else if(index==4){
				$('.previous-step').attr('data-index',index-1);
				$('.next-step').attr('data-index',index);
			}else{
				$('.previous-step').attr('data-index',index-1);
				$('.next-step').attr('data-index',index+1);
			}
			
			$('#prx-steps').find('ul.step-state').each(function(index) {
				var isMaxH = $(this).css('display');
				if( isMaxH != 'none') {
					if(index == 0) {
						$('.bottom-step-action').find('.previous-step').hide();
						$('.bottom-step-action').find('.next-step').show();
					}
					if(index == 1 || index == 2) {
						$('.bottom-step-action').find('.previous-step').show();
						$('.bottom-step-action').find('.next-step').show();
					}
					if(index == 3) {
						$('.bottom-step-action').find('.previous-step').show();
						$('.bottom-step-action').find('.next-step').hide();
					}
				}
			});

		}

		$(".toggle-details").click(function() {
			$('.prx-show-selected').slideToggle();
		});

		$('.next-step').click(function() {
			var target = parseInt($(this).attr('data-index'));
			var lastIndex = 0;
			$('.step-container .step-completed').each(function() {
				lastIndex = $(this).index() + 1;
			});
			if(target <= lastIndex){
				var previousIndex = $(this).attr('data-index');
				var previousStatus = 'step-status-' + previousIndex;
				setPrevNext(previousStatus);
			}
		});
		$('.previous-step').click(function() {
			var previousIndex = $(this).attr('data-index');
			var previousStatus = 'step-status-' + previousIndex;
		    setPrevNext(previousStatus, 'previous');
		});

		$(".desc a").click(function(e) {
        	e.stopPropagation();
   		});
		$(function () {
  			$('[data-toggle="tooltip"]').tooltip();
		});
	});
</script>

<style type="text/css">
	.prx-step-section{
		overflow: hidden;
	}
</style>