<?php
namespace RedChamps\GuestOrders\Block;

use Magento\Checkout\Model\Session;
use Magento\Customer\Api\AccountManagementInterface;
use Magento\Framework\View\Element\Template;
use RedChamps\GuestOrders\Model\ConfigReader;

class AccountSuccess extends Template
{
    /**
     * @var Session
     */
    private $checkoutSession;
    /**
     * @var ConfigReader
     */
    private $configReader;
    /**
     * @var AccountManagementInterface
     */
    private $accountManagement;

    public function __construct(
        Session $checkoutSession,
        ConfigReader $configReader,
        AccountManagementInterface $accountManagement,
        Template\Context $context,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->checkoutSession = $checkoutSession;
        $this->configReader = $configReader;
        $this->accountManagement = $accountManagement;
    }

    public function canShow()
    {
        $order = $this->checkoutSession->getLastRealOrder();
        if (
            $this->configReader->getConfig("auto_customer_accounts/email_notification") &&
            $this->configReader->getConfig("auto_customer_accounts/success_enabled") &&
            $this->configReader->getConfig("auto_customer_accounts/enabled") &&
            (
                $this->checkoutSession->getCustomerAutoGenerated() ||
                (
                    !$this->configReader->canProcessImmediately() &&
                    $order->getCustomerIsGuest() &&
                    !$order->getCustomerId() &&
                    $this->accountManagement->isEmailAvailable($order->getCustomerEmail())
                )
            )
        ) {
            $this->checkoutSession->setCustomerAutoGenerated(false);
            return true;
        }
        return false;
    }

    public function getText()
    {
        return $this->configReader->getConfig("auto_customer_accounts/success_text");
    }

    public function getStyles()
    {
        return $this->configReader->getConfig("auto_customer_accounts/success_styles");
    }
}
